version: '3.8'

services:

  api:
    build: ./services/api
    command: uvicorn app:app --host 0.0.0.0 --port 5555 --app-dir app --workers 1 --limit-concurrency 32 --reload
    volumes:
      - ./services/api/:/usr/src/app/
    ports:
      - "5555:5555"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    container_name: api

  web:
    image: img-static-site-example
    build:
      context: ./services/web
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api
    container_name: web

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/home/logs
    environment:
      - POSTGRES_USER=portfolio
      - POSTGRES_PASSWORD=portfolio
      - POSTGRES_DB=portfolio_dev
    container_name: postgresql

volumes:
  postgres_data:
