FROM nginx

# Copy web folder
COPY . /usr/share/nginx/html

# nginx config
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.prod.conf /etc/nginx/conf.d

# remove default logging to container logs
RUN rm /var/log/nginx/*
